repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-ast
      - id: check-toml
      - id: check-yaml
      - id: check-json
      - id: debug-statements
      - id: trailing-whitespace

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.24.1
    hooks:
      - id: validate-pyproject

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.9
    hooks:
      # Run the linter.
      - id: ruff
{%- if cookiecutter.code_formatter == 'Ruff' %}
      # Run the formatter.
      - id: ruff-format
        args: [--check]
{%- endif %}

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.3
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]
{% if cookiecutter.ci_provider != 'No CI' %}
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.33.0
    hooks:
{%- if cookiecutter.ci_provider == 'Github' %}
      - id: check-github-actions
      - id: check-github-workflows
        args: [--verbose]
{%- elif cookiecutter.ci_provider == 'Azure DevOps' %}
      - id: check-azure-pipelines
        files: ^\.azure-pipelines/.*\.(yaml|yml)$
        args: [--verbose]
{%- endif %}
{%- endif %}
{% if cookiecutter.code_formatter == 'Black' %}
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
{%- endif %}
