repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-ast
      - id: check-toml
      - id: check-yaml
      - id: check-json
      - id: debug-statements
      - id: trailing-whitespace

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.18
    hooks:
      - id: validate-pyproject

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.5
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --show-fixes]
{%- if cookiecutter.code_formatter == 'Ruff' %}
      # Run the formatter.
      - id: ruff-format
{%- endif %}
{% if cookiecutter.code_formatter == 'Black' %}
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
{% endif %}
