pr:
  branches:
    include:
      - main
      - release

jobs:
{%- if cookiecutter.project_type == 'Application' %}
  - job: RequirementsCheck
    displayName: 'Requirements check'
    steps:
      - checkout: self
        fetchDepth: 0

      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.12'
          addToPath: true

      - bash: |
          set -eo pipefail
          python -m pip install --upgrade pip
          pip install pipenv
        displayName: 'Install dependencies'

      - bash: |
          set -eo pipefail
          pipenv requirements | sed '/^-i /d' | diff --color=auto requirements/requirements.txt -
          pipenv requirements --dev-only | sed '/^-i /d' | diff --color=auto requirements/requirements-dev.txt -
          pipenv requirements --categories docs | sed '/^-i /d' | diff --color=auto requirements/requirements-docs.txt -
          pipenv requirements --categories style | sed '/^-i /d' | diff --color=auto requirements/requirements-style.txt -
        displayName: 'Check if requirements diff from pipenv and requirements.txt files'
{%- endif %}

  - job: TestMatrix
    displayName: 'Run Tests'
    strategy:
      matrix:
{%- if cookiecutter.project_type == 'Application' %}
        ubuntu_py_3_12:
          imageName: 'ubuntu-latest'
          pythonVersion: '3.12'
{%- elif cookiecutter.project_type == 'Library' %}
        ubuntu_py_3_12:
          imageName: 'ubuntu-latest'
          pythonVersion: '3.12'
        ubuntu_py_3_11:
          imageName: 'ubuntu-latest'
          pythonVersion: '3.11'
        ubuntu_py_3_10:
          imageName: 'ubuntu-latest'
          pythonVersion: '3.10'
        windows_py_3_12:
          imageName: 'windows-latest'
          pythonVersion: '3.12'
        windows_py_3_11:
          imageName: 'windows-latest'
          pythonVersion: '3.11'
        windows_py_3_10:
          imageName: 'windows-latest'
          pythonVersion: '3.10'
        macos_py_3_12:
          imageName: 'macos-latest'
          pythonVersion: '3.12'
        macos_py_3_11:
          imageName: 'macos-latest'
          pythonVersion: '3.11'
        macos_py_3_10:
          imageName: 'macos-latest'
          pythonVersion: '3.10'
{%- endif %}
    continueOnError: true
    pool:
      vmImage: $(imageName)
    steps:
      - checkout: self
        fetchDepth: 0

      - task: UsePythonVersion@0
        inputs:
          versionSpec: $(pythonVersion)
          addToPath: true

      - script: |
          python -m pip install --upgrade pip
          pip install tox
        displayName: 'Install dependencies'

      - script: |
          tox -e py$(pythonVersion) -vv -- -v
        displayName: 'Run test suite'

  - job: CheckStyleMatrix
    displayName: 'Check Style'
    strategy:
      matrix:
        type:
          tox_env: 'type'
          imageName: 'ubuntu-latest'
        lint:
          tox_env: 'lint'
          imageName: 'ubuntu-latest'
        format:
          tox_env: 'format'
          imageName: 'ubuntu-latest'
        docs:
          tox_env: 'docs'
          imageName: 'ubuntu-latest'
        bandit:
          tox_env: 'bandit'
          imageName: 'ubuntu-latest'
{%- if cookiecutter.git_init %}
        pre_commit:
          tox_env: 'pre-commit'
          imageName: 'ubuntu-latest'
{%- endif %}
    continueOnError: true
    pool:
      vmImage: $(imageName)
    steps:
      - checkout: self
        fetchDepth: 0

      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.12'
          addToPath: true

      - script: |
          python -m pip install --upgrade pip
          pip install tox
        displayName: 'Install dependencies'

      - script: |
          tox -e $(tox_env) -vv -- -v
        displayName: 'Run tox environment'
