# Minimal makefile for Sphinx documentation
#

# You can set these variables from the command line, and also
# from the environment for the first two.
SPHINXOPTS    ?=
SPHINXBUILD   ?= sphinx-build
SOURCEDIR     = .
BUILDDIR      = _build
PKG           = ../intropy

# Put it first so that "make" without argument is like "make help".
.PHONY: help
help:
	@$(SPHINXBUILD) -M help "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)

.PHONY: livehtml
livehtml:
	sphinx-autobuild -b html --open-browser --port 9000 --watch $(PKG) -c . $(SOURCEDIR) $(BUILDDIR)/html

.PHONY: apidocs
apidocs:
	sphinx-apidoc --maxdepth 2 --remove-old --separate --output-dir $(SOURCEDIR)/api $(PKG)

# Catch-all target: route all unknown targets to Sphinx using the new
# "make mode" option.  $(O) is meant as a shortcut for $(SPHINXOPTS).
.PHONY: Makefile
%: Makefile
	@$(SPHINXBUILD) -b $@ --jobs auto "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)
